import type { NextPage } from "next";
import Head from "next/head";
import AudioExample from "../components/AudioExample";
import VideoExample from "../components/VideoExample";
import { useState } from "react";
import { MusicNoteSimple, VideoCamera } from 'phosphor-react';

const Home: NextPage = () => {
    const [isAudioExample, setIsAudioExample] = useState(false);

    return <>
        <Head>
            <title>Create T3 App</title>
            <meta name="description" content="Generated by create-t3-app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex flex-col items-center">
            <section className="text-center p-8">
                <span className="py-1 px-3 rounded-full bg-red-500 text-white">
                    Experimental Release
                </span>
                <h1 className="font-black text-6xl sm:text-7xl text-slate-900">
                    React AV
                </h1>
                <h2 className="text-4xl text-slate-800">
                    Build modern media players with React.
                </h2>
                <p className="mt-4 text-xl text-slate-600">
                    Fully-featured, headless, hooks-based, and declarative media player framework for React.
                </p>

            </section>
            <section className="flex flex-col gap-2 w-full max-w-7xl items-center">
                <div className="flex flex-row gap-1 p-1 bg-slate-300 rounded-md">
                    <button className={"p-2 rounded flex flex-row gap-1 items-center transition" + (!isAudioExample ? " bg-slate-50" : " hover:bg-slate-200")} onClick={() => setIsAudioExample(false)}>
                        <VideoCamera size={16} />
                        Video
                    </button>
                    <button className={"p-2 rounded flex flex-row gap-1 items-center transition" + (isAudioExample ? " bg-slate-50" : " hover:bg-slate-200")} onClick={() => setIsAudioExample(true)}>
                        <MusicNoteSimple size={16} />
                        Audio
                    </button>
                </div>
                {
                    isAudioExample ? <AudioExample /> : <VideoExample />
                }
                {
                    isAudioExample ? <span className="text-xs">
                        <a href="https://lemondemon.bandcamp.com/track/dinosaurchestra-part-three" target="blank">Dinosaurchesra Part Three by Lemon Demon</a> is licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/3.0/" target="blank">CC BY-NC-SA 3.0</a>.
                    </span> : <span className="text-xs">
                        <a href="https://www.youtube.com/watch?v=_cMxraX_5RE" target="blank">Sprite Fright by Blender Studio</a> is licensed under <a href="https://studio.blender.org/films/sprite-fright/pages/about/" target="blank">CC BY 1.0</a> by <a href="https://studio.blender.org" target="blank">Blender Foundation</a>.
                    </span>
                }
            </section>
        </main>
    </>;
};

export default Home;
